//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 17.0.32112.339
// 
namespace Manager.ServiceManager {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CakesCategory", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class CakesCategory : Manager.ServiceManager.BaseEntity {
        
        private int CategoryCodeField;
        
        private string CategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((this.CategoryCodeField.Equals(value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.BuyDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.Buying))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.CakeDesserts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.Status))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.EventKind))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.BaseKind))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.DesignedPhotoGallery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.Orders))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.PicturesInCake))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.StockImages))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.Messages))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Manager.ServiceManager.CakesCategory))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Customer : Manager.ServiceManager.BaseEntity {
        
        private int CustomerCodeField;
        
        private string CustomerPasswordField;
        
        private string CustomerPhoneField;
        
        private string FirstNameField;
        
        private string GmailField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((this.CustomerCodeField.Equals(value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPhone {
            get {
                return this.CustomerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneField, value) != true)) {
                    this.CustomerPhoneField = value;
                    this.RaisePropertyChanged("CustomerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gmail {
            get {
                return this.GmailField;
            }
            set {
                if ((object.ReferenceEquals(this.GmailField, value) != true)) {
                    this.GmailField = value;
                    this.RaisePropertyChanged("Gmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyDetails", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class BuyDetails : Manager.ServiceManager.BaseEntity {
        
        private int AmountField;
        
        private Manager.ServiceManager.Buying BuyingCodeField;
        
        private Manager.ServiceManager.CakeDesserts CakeCodeField;
        
        private int DetailsCodeField;
        
        private Manager.ServiceManager.Status StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Buying BuyingCode {
            get {
                return this.BuyingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyingCodeField, value) != true)) {
                    this.BuyingCodeField = value;
                    this.RaisePropertyChanged("BuyingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.CakeDesserts CakeCode {
            get {
                return this.CakeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeCodeField, value) != true)) {
                    this.CakeCodeField = value;
                    this.RaisePropertyChanged("CakeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetailsCode {
            get {
                return this.DetailsCodeField;
            }
            set {
                if ((this.DetailsCodeField.Equals(value) != true)) {
                    this.DetailsCodeField = value;
                    this.RaisePropertyChanged("DetailsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Status StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Buying", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Buying : Manager.ServiceManager.BaseEntity {
        
        private int BuyingCodeField;
        
        private System.DateTime BuyingDateField;
        
        private int BuyingPriceField;
        
        private string BuyingTimeField;
        
        private string CreditCardField;
        
        private Manager.ServiceManager.Customer CustomerCodeField;
        
        private string CvvField;
        
        private string IdOfCardField;
        
        private bool IsShippingField;
        
        private string ShippingAddressField;
        
        private string ShippingPhoneField;
        
        private string ValidityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyingCode {
            get {
                return this.BuyingCodeField;
            }
            set {
                if ((this.BuyingCodeField.Equals(value) != true)) {
                    this.BuyingCodeField = value;
                    this.RaisePropertyChanged("BuyingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BuyingDate {
            get {
                return this.BuyingDateField;
            }
            set {
                if ((this.BuyingDateField.Equals(value) != true)) {
                    this.BuyingDateField = value;
                    this.RaisePropertyChanged("BuyingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyingPrice {
            get {
                return this.BuyingPriceField;
            }
            set {
                if ((this.BuyingPriceField.Equals(value) != true)) {
                    this.BuyingPriceField = value;
                    this.RaisePropertyChanged("BuyingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyingTime {
            get {
                return this.BuyingTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyingTimeField, value) != true)) {
                    this.BuyingTimeField = value;
                    this.RaisePropertyChanged("BuyingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditCard {
            get {
                return this.CreditCardField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditCardField, value) != true)) {
                    this.CreditCardField = value;
                    this.RaisePropertyChanged("CreditCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Customer CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv {
            get {
                return this.CvvField;
            }
            set {
                if ((object.ReferenceEquals(this.CvvField, value) != true)) {
                    this.CvvField = value;
                    this.RaisePropertyChanged("Cvv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdOfCard {
            get {
                return this.IdOfCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IdOfCardField, value) != true)) {
                    this.IdOfCardField = value;
                    this.RaisePropertyChanged("IdOfCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsShipping {
            get {
                return this.IsShippingField;
            }
            set {
                if ((this.IsShippingField.Equals(value) != true)) {
                    this.IsShippingField = value;
                    this.RaisePropertyChanged("IsShipping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingAddress {
            get {
                return this.ShippingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingAddressField, value) != true)) {
                    this.ShippingAddressField = value;
                    this.RaisePropertyChanged("ShippingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingPhone {
            get {
                return this.ShippingPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingPhoneField, value) != true)) {
                    this.ShippingPhoneField = value;
                    this.RaisePropertyChanged("ShippingPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Validity {
            get {
                return this.ValidityField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidityField, value) != true)) {
                    this.ValidityField = value;
                    this.RaisePropertyChanged("Validity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CakeDesserts", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class CakeDesserts : Manager.ServiceManager.BaseEntity {
        
        private Manager.ServiceManager.CakesCategory CakeCategoryField;
        
        private int CakeCodeField;
        
        private string CakeDetailsField;
        
        private string CakeNameField;
        
        private string CakePictureField;
        
        private int CakePriceField;
        
        private bool IsDairyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.CakesCategory CakeCategory {
            get {
                return this.CakeCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeCategoryField, value) != true)) {
                    this.CakeCategoryField = value;
                    this.RaisePropertyChanged("CakeCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CakeCode {
            get {
                return this.CakeCodeField;
            }
            set {
                if ((this.CakeCodeField.Equals(value) != true)) {
                    this.CakeCodeField = value;
                    this.RaisePropertyChanged("CakeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CakeDetails {
            get {
                return this.CakeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeDetailsField, value) != true)) {
                    this.CakeDetailsField = value;
                    this.RaisePropertyChanged("CakeDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CakeName {
            get {
                return this.CakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeNameField, value) != true)) {
                    this.CakeNameField = value;
                    this.RaisePropertyChanged("CakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CakePicture {
            get {
                return this.CakePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.CakePictureField, value) != true)) {
                    this.CakePictureField = value;
                    this.RaisePropertyChanged("CakePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CakePrice {
            get {
                return this.CakePriceField;
            }
            set {
                if ((this.CakePriceField.Equals(value) != true)) {
                    this.CakePriceField = value;
                    this.RaisePropertyChanged("CakePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDairy {
            get {
                return this.IsDairyField;
            }
            set {
                if ((this.IsDairyField.Equals(value) != true)) {
                    this.IsDairyField = value;
                    this.RaisePropertyChanged("IsDairy");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Status : Manager.ServiceManager.BaseEntity {
        
        private int StatusCodeField;
        
        private string StatusNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventKind", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class EventKind : Manager.ServiceManager.BaseEntity {
        
        private int EventKindCodeField;
        
        private string EventKindNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventKindCode {
            get {
                return this.EventKindCodeField;
            }
            set {
                if ((this.EventKindCodeField.Equals(value) != true)) {
                    this.EventKindCodeField = value;
                    this.RaisePropertyChanged("EventKindCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventKindName {
            get {
                return this.EventKindNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKindNameField, value) != true)) {
                    this.EventKindNameField = value;
                    this.RaisePropertyChanged("EventKindName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseKind", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class BaseKind : Manager.ServiceManager.BaseEntity {
        
        private int KindCodeField;
        
        private string KindNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KindCode {
            get {
                return this.KindCodeField;
            }
            set {
                if ((this.KindCodeField.Equals(value) != true)) {
                    this.KindCodeField = value;
                    this.RaisePropertyChanged("KindCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KindName {
            get {
                return this.KindNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KindNameField, value) != true)) {
                    this.KindNameField = value;
                    this.RaisePropertyChanged("KindName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DesignedPhotoGallery", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class DesignedPhotoGallery : Manager.ServiceManager.BaseEntity {
        
        private Manager.ServiceManager.BaseKind BaseKindField;
        
        private int DesignedCakeCodeField;
        
        private string DetailsField;
        
        private Manager.ServiceManager.EventKind EventKindField;
        
        private string PictureField;
        
        private int PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.BaseKind BaseKind {
            get {
                return this.BaseKindField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseKindField, value) != true)) {
                    this.BaseKindField = value;
                    this.RaisePropertyChanged("BaseKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesignedCakeCode {
            get {
                return this.DesignedCakeCodeField;
            }
            set {
                if ((this.DesignedCakeCodeField.Equals(value) != true)) {
                    this.DesignedCakeCodeField = value;
                    this.RaisePropertyChanged("DesignedCakeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.EventKind EventKind {
            get {
                return this.EventKindField;
            }
            set {
                if ((object.ReferenceEquals(this.EventKindField, value) != true)) {
                    this.EventKindField = value;
                    this.RaisePropertyChanged("EventKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orders", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Orders : Manager.ServiceManager.BaseEntity {
        
        private Manager.ServiceManager.Buying BuyingCodeField;
        
        private Manager.ServiceManager.DesignedPhotoGallery CakeExampleCodeField;
        
        private Manager.ServiceManager.BaseKind CakeKindField;
        
        private System.DateTime DateGoalField;
        
        private int OrderCodeField;
        
        private int PriceField;
        
        private string RemarksField;
        
        private Manager.ServiceManager.Status StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Buying BuyingCode {
            get {
                return this.BuyingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyingCodeField, value) != true)) {
                    this.BuyingCodeField = value;
                    this.RaisePropertyChanged("BuyingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.DesignedPhotoGallery CakeExampleCode {
            get {
                return this.CakeExampleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeExampleCodeField, value) != true)) {
                    this.CakeExampleCodeField = value;
                    this.RaisePropertyChanged("CakeExampleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.BaseKind CakeKind {
            get {
                return this.CakeKindField;
            }
            set {
                if ((object.ReferenceEquals(this.CakeKindField, value) != true)) {
                    this.CakeKindField = value;
                    this.RaisePropertyChanged("CakeKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateGoal {
            get {
                return this.DateGoalField;
            }
            set {
                if ((this.DateGoalField.Equals(value) != true)) {
                    this.DateGoalField = value;
                    this.RaisePropertyChanged("DateGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderCode {
            get {
                return this.OrderCodeField;
            }
            set {
                if ((this.OrderCodeField.Equals(value) != true)) {
                    this.OrderCodeField = value;
                    this.RaisePropertyChanged("OrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Status StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PicturesInCake", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class PicturesInCake : Manager.ServiceManager.BaseEntity {
        
        private int CombinePictureCodeField;
        
        private Manager.ServiceManager.Orders OrderCodeField;
        
        private string PictureFileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CombinePictureCode {
            get {
                return this.CombinePictureCodeField;
            }
            set {
                if ((this.CombinePictureCodeField.Equals(value) != true)) {
                    this.CombinePictureCodeField = value;
                    this.RaisePropertyChanged("CombinePictureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Orders OrderCode {
            get {
                return this.OrderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCodeField, value) != true)) {
                    this.OrderCodeField = value;
                    this.RaisePropertyChanged("OrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureFile {
            get {
                return this.PictureFileField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureFileField, value) != true)) {
                    this.PictureFileField = value;
                    this.RaisePropertyChanged("PictureFile");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockImages", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class StockImages : Manager.ServiceManager.BaseEntity {
        
        private int ImageCodeField;
        
        private string ImageFileField;
        
        private string ImageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageCode {
            get {
                return this.ImageCodeField;
            }
            set {
                if ((this.ImageCodeField.Equals(value) != true)) {
                    this.ImageCodeField = value;
                    this.RaisePropertyChanged("ImageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageFile {
            get {
                return this.ImageFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageFileField, value) != true)) {
                    this.ImageFileField = value;
                    this.RaisePropertyChanged("ImageFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Messages : Manager.ServiceManager.BaseEntity {
        
        private string ContentField;
        
        private Manager.ServiceManager.Customer CustomerCodeField;
        
        private bool IsCustomerField;
        
        private bool IsReadField;
        
        private int MessageCodeField;
        
        private string TopicField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Manager.ServiceManager.Customer CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomer {
            get {
                return this.IsCustomerField;
            }
            set {
                if ((this.IsCustomerField.Equals(value) != true)) {
                    this.IsCustomerField = value;
                    this.RaisePropertyChanged("IsCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((this.MessageCodeField.Equals(value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceManager.IManager")]
    public interface IManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/IsMeneger", ReplyAction="http://tempuri.org/IManager/IsMenegerResponse")]
        System.Threading.Tasks.Task<bool> IsMenegerAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllCategories", ReplyAction="http://tempuri.org/IManager/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakesCategory>> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllCustomers", ReplyAction="http://tempuri.org/IManager/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetNextCategoryKey", ReplyAction="http://tempuri.org/IManager/GetNextCategoryKeyResponse")]
        System.Threading.Tasks.Task<int> GetNextCategoryKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddNewCategory", ReplyAction="http://tempuri.org/IManager/AddNewCategoryResponse")]
        System.Threading.Tasks.Task AddNewCategoryAsync(Manager.ServiceManager.CakesCategory category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetCustomerByName", ReplyAction="http://tempuri.org/IManager/GetCustomerByNameResponse")]
        System.Threading.Tasks.Task<Manager.ServiceManager.Customer> GetCustomerByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddNewCustomer", ReplyAction="http://tempuri.org/IManager/AddNewCustomerResponse")]
        System.Threading.Tasks.Task AddNewCustomerAsync(Manager.ServiceManager.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/UpdateCustomer", ReplyAction="http://tempuri.org/IManager/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(Manager.ServiceManager.Customer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetBuyDetails", ReplyAction="http://tempuri.org/IManager/GetBuyDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetBuyDetailsAsync(int codeBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllBuyings", ReplyAction="http://tempuri.org/IManager/GetAllBuyingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Buying>> GetAllBuyingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllCakeDesserts", ReplyAction="http://tempuri.org/IManager/GetAllCakeDessertsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakeDesserts>> GetAllCakeDessertsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetNextBuyingKey", ReplyAction="http://tempuri.org/IManager/GetNextBuyingKeyResponse")]
        System.Threading.Tasks.Task<int> GetNextBuyingKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllEventsKind", ReplyAction="http://tempuri.org/IManager/GetAllEventsKindResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.EventKind>> GetAllEventsKindAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllBaseKind", ReplyAction="http://tempuri.org/IManager/GetAllBaseKindResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BaseKind>> GetAllBaseKindAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllDesignedPhotoGallery", ReplyAction="http://tempuri.org/IManager/GetAllDesignedPhotoGalleryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.DesignedPhotoGallery>> GetAllDesignedPhotoGalleryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetDesignedPhotoGalleriesByBaseKindAndEvent", ReplyAction="http://tempuri.org/IManager/GetDesignedPhotoGalleriesByBaseKindAndEventResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.DesignedPhotoGallery>> GetDesignedPhotoGalleriesByBaseKindAndEventAsync(int baseKind, int eventKind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrderByCodeBuying", ReplyAction="http://tempuri.org/IManager/GetOrderByCodeBuyingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrderByCodeBuyingAsync(int codeBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddBuying", ReplyAction="http://tempuri.org/IManager/AddBuyingResponse")]
        System.Threading.Tasks.Task AddBuyingAsync(Manager.ServiceManager.Buying buying, System.Collections.Generic.List<Manager.ServiceManager.BuyDetails> buyDetails, System.Collections.Generic.List<Manager.ServiceManager.Orders> orders, System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake> pics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetStatusByCode", ReplyAction="http://tempuri.org/IManager/GetStatusByCodeResponse")]
        System.Threading.Tasks.Task<Manager.ServiceManager.Status> GetStatusByCodeAsync(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllbuyDetails", ReplyAction="http://tempuri.org/IManager/GetAllbuyDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetAllbuyDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetBuyingsByCustomer", ReplyAction="http://tempuri.org/IManager/GetBuyingsByCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Buying>> GetBuyingsByCustomerAsync(Manager.ServiceManager.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetBuyDetailsByBuying", ReplyAction="http://tempuri.org/IManager/GetBuyDetailsByBuyingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetBuyDetailsByBuyingAsync(int buying);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrdersByBuying", ReplyAction="http://tempuri.org/IManager/GetOrdersByBuyingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByBuyingAsync(int buying);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetImage", ReplyAction="http://tempuri.org/IManager/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddPictureInCake", ReplyAction="http://tempuri.org/IManager/AddPictureInCakeResponse")]
        System.Threading.Tasks.Task AddPictureInCakeAsync(Manager.ServiceManager.PicturesInCake pic, byte[] fileImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetCakeDessertsByCategoryCode", ReplyAction="http://tempuri.org/IManager/GetCakeDessertsByCategoryCodeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakeDesserts>> GetCakeDessertsByCategoryCodeAsync(int cakesCategoryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/UpdateCakeDessert", ReplyAction="http://tempuri.org/IManager/UpdateCakeDessertResponse")]
        System.Threading.Tasks.Task UpdateCakeDessertAsync(Manager.ServiceManager.CakeDesserts cakeDesserts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddNewCakeDesserts", ReplyAction="http://tempuri.org/IManager/AddNewCakeDessertsResponse")]
        System.Threading.Tasks.Task AddNewCakeDessertsAsync(Manager.ServiceManager.CakeDesserts c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllStockImages", ReplyAction="http://tempuri.org/IManager/GetAllStockImagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.StockImages>> GetAllStockImagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/UpdateCategory", ReplyAction="http://tempuri.org/IManager/UpdateCategoryResponse")]
        System.Threading.Tasks.Task UpdateCategoryAsync(Manager.ServiceManager.CakesCategory category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetNextCakeKey", ReplyAction="http://tempuri.org/IManager/GetNextCakeKeyResponse")]
        System.Threading.Tasks.Task<int> GetNextCakeKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetNextMessagesKey", ReplyAction="http://tempuri.org/IManager/GetNextMessagesKeyResponse")]
        System.Threading.Tasks.Task<int> GetNextMessagesKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddNewMessages", ReplyAction="http://tempuri.org/IManager/AddNewMessagesResponse")]
        System.Threading.Tasks.Task AddNewMessagesAsync(Manager.ServiceManager.Messages messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllMessages", ReplyAction="http://tempuri.org/IManager/GetAllMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Messages>> GetAllMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetMessagesByCustomer", ReplyAction="http://tempuri.org/IManager/GetMessagesByCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Messages>> GetMessagesByCustomerAsync(Manager.ServiceManager.Customer o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/ReadAllMessages", ReplyAction="http://tempuri.org/IManager/ReadAllMessagesResponse")]
        System.Threading.Tasks.Task ReadAllMessagesAsync(Manager.ServiceManager.Customer o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllOrders", ReplyAction="http://tempuri.org/IManager/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrdersByStatus", ReplyAction="http://tempuri.org/IManager/GetOrdersByStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByStatusAsync(int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrdersByDate", ReplyAction="http://tempuri.org/IManager/GetOrdersByDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/UpdatOrder", ReplyAction="http://tempuri.org/IManager/UpdatOrderResponse")]
        System.Threading.Tasks.Task UpdatOrderAsync(Manager.ServiceManager.Orders o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrdersByCustomer", ReplyAction="http://tempuri.org/IManager/GetOrdersByCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByCustomerAsync(Manager.ServiceManager.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetOrdersByWeek", ReplyAction="http://tempuri.org/IManager/GetOrdersByWeekResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByWeekAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAllPictures", ReplyAction="http://tempuri.org/IManager/GetAllPicturesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake>> GetAllPicturesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetPicturesByOrderCode", ReplyAction="http://tempuri.org/IManager/GetPicturesByOrderCodeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake>> GetPicturesByOrderCodeAsync(Manager.ServiceManager.Orders o);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagerChannel : Manager.ServiceManager.IManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagerClient : System.ServiceModel.ClientBase<Manager.ServiceManager.IManager>, Manager.ServiceManager.IManager {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ManagerClient() : 
                base(ManagerClient.GetDefaultBinding(), ManagerClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IManager.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerClient(EndpointConfiguration endpointConfiguration) : 
                base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), ManagerClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<bool> IsMenegerAsync(string userName, string password) {
            return base.Channel.IsMenegerAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakesCategory>> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetNextCategoryKeyAsync() {
            return base.Channel.GetNextCategoryKeyAsync();
        }
        
        public System.Threading.Tasks.Task AddNewCategoryAsync(Manager.ServiceManager.CakesCategory category) {
            return base.Channel.AddNewCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<Manager.ServiceManager.Customer> GetCustomerByNameAsync(string name) {
            return base.Channel.GetCustomerByNameAsync(name);
        }
        
        public System.Threading.Tasks.Task AddNewCustomerAsync(Manager.ServiceManager.Customer c) {
            return base.Channel.AddNewCustomerAsync(c);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(Manager.ServiceManager.Customer c) {
            return base.Channel.UpdateCustomerAsync(c);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetBuyDetailsAsync(int codeBuy) {
            return base.Channel.GetBuyDetailsAsync(codeBuy);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Buying>> GetAllBuyingsAsync() {
            return base.Channel.GetAllBuyingsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakeDesserts>> GetAllCakeDessertsAsync() {
            return base.Channel.GetAllCakeDessertsAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetNextBuyingKeyAsync() {
            return base.Channel.GetNextBuyingKeyAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.EventKind>> GetAllEventsKindAsync() {
            return base.Channel.GetAllEventsKindAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BaseKind>> GetAllBaseKindAsync() {
            return base.Channel.GetAllBaseKindAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.DesignedPhotoGallery>> GetAllDesignedPhotoGalleryAsync() {
            return base.Channel.GetAllDesignedPhotoGalleryAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.DesignedPhotoGallery>> GetDesignedPhotoGalleriesByBaseKindAndEventAsync(int baseKind, int eventKind) {
            return base.Channel.GetDesignedPhotoGalleriesByBaseKindAndEventAsync(baseKind, eventKind);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrderByCodeBuyingAsync(int codeBuy) {
            return base.Channel.GetOrderByCodeBuyingAsync(codeBuy);
        }
        
        public System.Threading.Tasks.Task AddBuyingAsync(Manager.ServiceManager.Buying buying, System.Collections.Generic.List<Manager.ServiceManager.BuyDetails> buyDetails, System.Collections.Generic.List<Manager.ServiceManager.Orders> orders, System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake> pics) {
            return base.Channel.AddBuyingAsync(buying, buyDetails, orders, pics);
        }
        
        public System.Threading.Tasks.Task<Manager.ServiceManager.Status> GetStatusByCodeAsync(int code) {
            return base.Channel.GetStatusByCodeAsync(code);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetAllbuyDetailsAsync() {
            return base.Channel.GetAllbuyDetailsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Buying>> GetBuyingsByCustomerAsync(Manager.ServiceManager.Customer customer) {
            return base.Channel.GetBuyingsByCustomerAsync(customer);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.BuyDetails>> GetBuyDetailsByBuyingAsync(int buying) {
            return base.Channel.GetBuyDetailsByBuyingAsync(buying);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByBuyingAsync(int buying) {
            return base.Channel.GetOrdersByBuyingAsync(buying);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string fileName) {
            return base.Channel.GetImageAsync(fileName);
        }
        
        public System.Threading.Tasks.Task AddPictureInCakeAsync(Manager.ServiceManager.PicturesInCake pic, byte[] fileImage) {
            return base.Channel.AddPictureInCakeAsync(pic, fileImage);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.CakeDesserts>> GetCakeDessertsByCategoryCodeAsync(int cakesCategoryCode) {
            return base.Channel.GetCakeDessertsByCategoryCodeAsync(cakesCategoryCode);
        }
        
        public System.Threading.Tasks.Task UpdateCakeDessertAsync(Manager.ServiceManager.CakeDesserts cakeDesserts) {
            return base.Channel.UpdateCakeDessertAsync(cakeDesserts);
        }
        
        public System.Threading.Tasks.Task AddNewCakeDessertsAsync(Manager.ServiceManager.CakeDesserts c) {
            return base.Channel.AddNewCakeDessertsAsync(c);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.StockImages>> GetAllStockImagesAsync() {
            return base.Channel.GetAllStockImagesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateCategoryAsync(Manager.ServiceManager.CakesCategory category) {
            return base.Channel.UpdateCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<int> GetNextCakeKeyAsync() {
            return base.Channel.GetNextCakeKeyAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetNextMessagesKeyAsync() {
            return base.Channel.GetNextMessagesKeyAsync();
        }
        
        public System.Threading.Tasks.Task AddNewMessagesAsync(Manager.ServiceManager.Messages messages) {
            return base.Channel.AddNewMessagesAsync(messages);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Messages>> GetAllMessagesAsync() {
            return base.Channel.GetAllMessagesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Messages>> GetMessagesByCustomerAsync(Manager.ServiceManager.Customer o) {
            return base.Channel.GetMessagesByCustomerAsync(o);
        }
        
        public System.Threading.Tasks.Task ReadAllMessagesAsync(Manager.ServiceManager.Customer o) {
            return base.Channel.ReadAllMessagesAsync(o);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByStatusAsync(int status) {
            return base.Channel.GetOrdersByStatusAsync(status);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByDateAsync(System.DateTime date) {
            return base.Channel.GetOrdersByDateAsync(date);
        }
        
        public System.Threading.Tasks.Task UpdatOrderAsync(Manager.ServiceManager.Orders o) {
            return base.Channel.UpdatOrderAsync(o);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByCustomerAsync(Manager.ServiceManager.Customer customer) {
            return base.Channel.GetOrdersByCustomerAsync(customer);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.Orders>> GetOrdersByWeekAsync(System.DateTime date) {
            return base.Channel.GetOrdersByWeekAsync(date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake>> GetAllPicturesAsync() {
            return base.Channel.GetAllPicturesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Manager.ServiceManager.PicturesInCake>> GetPicturesByOrderCodeAsync(Manager.ServiceManager.Orders o) {
            return base.Channel.GetPicturesByOrderCodeAsync(o);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IManager)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IManager)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServer/Manager/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ManagerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IManager);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ManagerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IManager);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IManager,
        }
    }
}
